# Generated by Django 2.1.5 on 2019-01-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('appName', models.CharField(max_length=30)),
                ('IpAddress', models.GenericIPAddressField()),
                ('appCode', models.CharField(max_length=30)),
                ('companyName', models.CharField(max_length=255)),
                ('webAddress', models.CharField(max_length=255)),
                ('callBackUrl', models.CharField(max_length=255)),
                ('activityType', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
