# Generated by Django 2.1.5 on 2019-01-30 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finnoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'verbose_name': 'app', 'verbose_name_plural': 'apps'},
        ),
    ]
