# Generated by Django 2.1.5 on 2019-01-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finnoapp', '0002_auto_20190130_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='created_on',
        ),
        migrations.AlterField(
            model_name='app',
            name='IpAddress',
            field=models.CharField(max_length=30),
        ),
    ]
