# Generated by Django 2.1.5 on 2019-01-30 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finnoapp', '0003_auto_20190130_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
